# Generated by Django 5.0.2 on 2024-03-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_email_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
